- src/templates/learn-doc.js
addresses https://trello.com/c/MjFJvZAI
> Update learn doc template to match wireframe

- src/components/left-nav.js
addresses https://trello.com/c/a1JmSFPm
> Remove TreeChevron, move functions around, change ml-5 on ul to ml-4

- src/components/side-navigation.js
> Add side navigation footer links

- src/components/left-nav.js
> Add appropriate classes to section headers in left nav

- src/components/left-nav.js
- src/templates/doc.js
- src/templates/learn-doc.js
Doc with more than one version
Doc with one version only
Learn doc
> Create SectionHeader and SectionHeaderWithVersions

- src/components/card-decks.js
- src/templates/learn-doc.js
> learn doc cards

- src/components/left-nav.js
> Use static text in version area for single version

- src/components/katacoda.js
- src/styles/_docs.css
For advocacy docs. Usage in .mdx:
import Katacoda from '../../../../src/components/katacoda';
... some markdown ...
<Katacoda account="shog9" scenario="java-jdbc" />
> Add Katacoda embed component

- src/components/layout.js
- src/styles/_helpers.scss
- src/styles/_overrides.scss
- src/styles/_theme.scss
> code style

- src/components/search/index.js
> Fix NoResults conditional, create smarter SearchDivider component

- src/components/index-links.js
- src/components/left-nav.js
- src/components/search/hitComps.js
- src/constants/index-link-list.js
- src/constants/products.js
> add icons to idex-links

- src/components/advanced-search/form.js
- src/components/advanced-search/results.js
- Block form submission
- Next page navigation under specific index if needed
> fix two advanced search bugs

- docs/playground/1/01_examples/copy.mdx
- src/components/back-button.js
- src/components/index.js
- src/components/left-nav.js
- src/components/prev-next.js
- src/components/tree-node.js
- src/constants/utils.js
Breaking up left-nav a bit by importing a function and a component instead of including it. Minor name cleanup
> clean up messes

- gatsby-config.js
merging this is to see what happens :)
> advo traits

- .gitignore
- src/components/index-links.js
- src/components/left-nav.js
- src/constants/index-link-list.js
- src/pages/index.js
I need some help with these guys:
(Top two sections aren't products, so don't have product icons per se, but I think we need a way of specifying them in left-nav.js)
> Styling product icons

- gatsby-node.js
- src/components/pdf-download.js
- src/pages/index.js
- src/styles/_overrides.scss
- src/templates/doc.js
* version numbers in page titles
* design for PDF downloads
* Product Index Links, ensuring that frontmatter values match
* Remove "snippets" from product index template
> Design updates

- gatsby-config.js
- disable partial index updates
> Production deploy Sept 11 2020

- src/components/left-nav.js
- src/components/pdf-download.js
- src/components/version-dropdown.js
- src/constants/index-link-list.js
- src/pages/index.js
- src/styles/_helpers.scss
- src/styles/_overrides.scss
- src/templates/doc.js
…e semantic with a helper class for position-relative
> Semantic CSS fix / Matt's Dropdown Fix Fix / Broken Links on Index / PDF Download Link location

- .github/ISSUE_TEMPLATE/documentation-feedback.md
- src/components/icon/iconNames.js
- src/components/icon/iconType.js
I think I need to have this in the master branch before it will show up in the link
> ISSUE_TEMPLATE

- src/pages/index.js
- src/templates/learn-doc.js
Merge in index and card-nav changes from the advocacy repo to reflect new nav structure
> Merge index changes from advo PR 99
